### PR TITLE
Allow styled-components 5 peer-dependency

### PR DESCRIPTION
**Pull request by spawnia**
There are no breaking changes in styled-components v5, so this is safe.

https://github.com/styled-components/styled-components/releases/tag/v5.0.0

### CODE REVIEW

**Comment by spawnia** [comment]
@azz can you take a look? I think this change would benefit many users.

**Comment by ronaldruzicka** [comment]
How does it look? It's almost a year now. Can it be merged?

**Comment by spawnia** [comment]
@azz If you no longer want to support this package, that is completely fine.

A deprecation notice and archival of the project would be nice in that case, so that developers will know to look somewhere else if they need updates like this.

Anyways, thank you for this package. It has worked well for us.

**Comment by runk** [comment]
Bump

**Pull request closed without merging**
