### PR TITLE
feat/Add grid height property

### PR DESCRIPTION
**Pull request by Ruskyj**
Added ability to specify Grid height (for example for full-screen layouts). It could be added by style={} property in JSX, but that's ugly.

### CODE REVIEW

**Comment by Ruskyj** [comment]
Sorry for previous PR, I screwed up your tests with moving the functions to inline style...

**Comment by azz** [comment]
Ignore commit bot, I thought I turned it off!

**Comment by Ruskyj** [comment]
Thx for quick response ;) .
Btw, any reason why you have most of functions in Grid.js outside the styled component (compared to Cell.js, where everything is inline)?

**Comment by azz** [comment]
No real reason, couldn't decide which I preferred so I guess I went with both 🤷‍♂️

**Comment by azz** [comment]
Sorry, this flew under the radar - merging once CI is green.

**Pull request merged**
