### PR TITLE
Fix middle style across browsers

### PR DESCRIPTION
**Pull request by jvgreenaway**
I noticed that there was a bug in Firefox when using the `middle` prop and opened https://github.com/azz/styled-css-grid/issues/45. I then also noticed the same issue appears is Edge.

Removing the `align-content: space-around` styled completely fixes the issue and does not appear to cause any issues with any other demos. 

Here are some screenshots from various browsers of the offending demo:

## Safari
safari

## Chrome
chrome

## Firefox
firefox

## Edge
edge

### CODE REVIEW

**Comment by azz** [comment]
Thanks! You just need to run `yarn test -u` to update the snapshots so the build passes 😄

**Comment by jvgreenaway** [comment]
Done 😄

**Comment by jvgreenaway** [comment]
Awesome! Thanks for this great library

**Pull request merged**
